### PR TITLE
This commit partially reverts the previous commit of link below.

### PR DESCRIPTION
**Pull request by arunmmanoharan**
https://github.com/a2441918/build/commit/8de72a547880d228ab0b41029a6c6c0c71a7d558

### CODE REVIEW

**Comment by arunmmanoharan** [comment]
Hi, I have a problem with AICP building for Xperia Z1. I get this error.

realmake: **\* No rule to make target `/home/audiogod/aicp/out/target/product/honami/recovery/bootrec-device', needed by`/home/audiogod/aicp/out/target/product/honami/boot.img'. Stop.
realmake: **\* Waiting for unfinished jobs...

Can u help me out. I have a proper tree and other roms for Xperia Z1 build fine.

**Comment by n3ocort3x** [comment]
If i would know.. im fighting against the same error on m8 atm, if i know something i post... i guess those patches are not enough

**Comment by arunmmanoharan** [comment]
M8, I built AICP and posted it mate. Check it out, but no audio sounds though. Some issue with sound drivers in ur source. carbon works fine same built by me.

**Comment by arunmmanoharan** [comment]
Nd bootrec-device is only for sony devices not htc ones.

**Comment by n3ocort3x** [comment]
thanks for letting me know... so u built m8 and u had no problems with building... ?? i get this error:

make: **\* No rule to make target `/home/n3ocort3x/AICP44/out/target/product/m8/kernel', needed by`/home/n3ocort3x/AICP44/out/target/product/m8/boot.img'.  Stop

have ur commits solved this ??

**Comment by arunmmanoharan** [comment]
did u add kernel files? I guess they werent added. 

No bugs at all in building, not even one.

**Comment by arunmmanoharan** [comment]
Well if I get the sound to work, make M8 official bro.

**Comment by Zipsnet** [comment]
You should not merge from github, you guys need to push to gerrit and merge from there, otherwise gerrit will delete this merge

**Comment by n3ocort3x** [comment]
before i can look into sound i have to get it building lol.... u mean add kernel to local manifest right...

i have kernel_htc_m8, then device htc_m8 and the 2 caf-new repos.. anything additionaylly needed ??

**Comment by n3ocort3x** [comment]
sorry hector.. davor told me to merge becuase imworking on m8.. wasnt aware
of this

2014-05-12 19:44 GMT+02:00 Zipsnet notifications@github.com:

**Comment by arunmmanoharan** [comment]
@Zipsnet  I am sorry, and can u help me with the gerrit process? I am a noob in gerrit.

@n3ocort3x  not that kernel, use kernel/htc/msm8974. Any doubts, see cm.dependancies for a more clear view.

**Comment by n3ocort3x** [comment]
i know and i have eveything in there... will reccheck and in the moment it
builds i come back to u

2014-05-12 19:46 GMT+02:00 Arun Manohar Manoharan notifications@github.com
:

**Comment by arunmmanoharan** [comment]
the kernel which u used is a wrong one.use the one which I mentioned, but I think u will face the same sound issues which I faced.

**Comment by n3ocort3x** [comment]
what exactly is the issue ?? i think i get it now building.. found the derp

2014-05-12 19:48 GMT+02:00 Arun Manohar Manoharan notifications@github.com
:

**Comment by arunmmanoharan** [comment]
change the kernel and all is well.

**Comment by n3ocort3x** [comment]
ok now i get this:

make: **\* No rule to make target `/home/n3ocort3x/AICP44/out/host/linux-x86/bin/dtbToolCM', needed by`/home/n3ocort3x/AICP44/out/target/product/m8/dt.img'.  Stop.

**Comment by arunmmanoharan** [comment]
dude do a make clean, add the kernel which i mentioned and a new sync again and start.

**Comment by arunmmanoharan** [comment]
can u link me where audio drivers in aicp are present? may be i can patch them for m8.

**Comment by arunmmanoharan** [comment]
USe this as ur local manifest

  <project name="a2441918/android_device_htc_m8" path="device/htc/m8" remote="ls" revision="kitkat" />
  <project name="LiquidSmooth/android_kernel_htc_msm8974" path="kernel/htc/msm8974" remote="ls" revision="kitkat" />
  <project name="CyanogenMod/android_device_qcom_common" path="device/qcom/common" remote="github" revision="cm-11.0" />
  <project name="LiquidSmooth/android_hardware_qcom_display-caf-new" path="hardware/qcom/display-caf-new" remote="ls" revision="kitkat" />
  <project name="LiquidSmooth/android_hardware_qcom_media-caf-new" path="hardware/qcom/media-caf-new" remote="ls" revision="kitkat" />
  <project name="CyanogenMod/android_hardware_qcom_fm" path="hardware/qcom/fm" remote="github" revision="cm-11.0" />

**Comment by n3ocort3x** [comment]
already building.. missed dtbtool from cm

2014-05-12 19:54 GMT+02:00 Arun Manohar Manoharan notifications@github.com
:

**Comment by n3ocort3x** [comment]
ok i got it booting.. and what sound issues are u talking about ???

2014-05-12 19:55 GMT+02:00 Peter Hofinger peter.hofinger@gmail.com:

**Comment by arunmmanoharan** [comment]
Like I dont get audio in aicp but in other roms i have sound.

**Comment by n3ocort3x** [comment]
strange .. my build works flawlessly s far

2014-05-13 4:26 GMT+02:00 Arun Manohar Manoharan notifications@github.com:

> Like I dont get audio in aicp but in other roms i have sound.

**Comment by arunmmanoharan** [comment]
Okay, I made a new build uploading now. Will post it.

Thanking You,
Yours sincerely,
Arun Manohar Manoharan.
+919994418176

**Pull request merged**
